version: '3.8'

services:
  halcyon:
    container_name: halcyon-app
    restart: always
    env_file:
      - ./.env
    build:
      context: .
      target: prod
    ports:
      - '${PORT}:${PORT}'
    volumes: 
      - nodemodules:/app/node_modules
      - ./:/app
    links:
      - mongo

  mongo:
    image: mongo
    container_name: halcyon-mongo-instance
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

volumes: 
  nodemodules: