version: "3.8"

services:
  halcyon:
    container_name: halcyon-app
    restart: always
    env_file:
      - ./.env
    environment:
      PORT: ${PORT}
    build:
      context: .
      target: prod
    ports:
      - "${PORT}:${PORT}"
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_started

  mongo:
    image: mongo
    container_name: halcyon-mongo-instance
    env_file:
      - ./.env
    restart: unless-stopped
    command: [ "-f", "/etc/mongo/mongod.conf", "--port", "${MONGO_PORT}" ]
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_LOG_DIR: "/dev/null"
    volumes:
      - ./mongo/data/:/data/db/
      - ./mongo/mongod.conf:/etc/mongo/mongod.conf
      - ./mongo/initdb.d/:/docker-entrypoint-initdb.d/
    expose:
      - 27799
    logging:
      driver: "local"
      options:
        max-file: "5"
        max-size: "50m"